// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
$(document).ready(function(){
	
	$(".jumbotron-banner").css("min-height" , $(window).height() - $(".navbar-inverse").height()) ;
	$(".jumbotron-banner .text-container .col-md-5").height($(".jumbotron-banner .text-container .col-md-7").outerHeight()).css("position","relative");
	
    var navheight = $(".navbar-inverse").height();

    $(".jumbotron-banner").css("margin-top", navheight);

	if ($(window).width() < 667) {
		setTimeout(function(){ 
			$(".cb-slideshow").height($(".cb-slideshow").height());
			$(".jumbotron-banner .text-container").css("padding-top", $(".cb-slideshow").height());
		},300);
	}
	

	$(".article a.learn-more").click(function(e){
		$(this).parent().next().toggle();
		e.preventDefault();
	});


    $(".navbar-nav > li").each(function(n){
        n++;
        $(this).addClass("nav-item-"+n);
    });

    // $(document).scroll(function (event){
    //     var scroll = $("[data-spy='affix']");
    //     if (scroll < 300){
    //         $(".quotes").hide();
    //         $(".quote-1").fadeIn("slow");
    //     }
    // });
    $(document).scroll(function (event) {

        // if($("body").attr("id") == "homepage"){
        //     //$("body").removeAttr("id");
        //     $(".footer").css("position","relative").fadeIn();
        // }

    // var scroll = $("[data-spy='affix']").offset().top;
    // //$("[data-spy='affix']").html(scroll+" "+ $("[data-spy='affix']").html());
    // if(scroll < 300){
    //     $("#animation").attr("src", "images/image.jpg");
    //     $(".quotes").hide();
    //     $(".quote-1").fadeIn("slow");

    //     $('.quotes').stop().fadeOut('normal', function(){
    //         $('.quote-1').stop().fadeIn();
    //     });
    // }
    // if(scroll >= 300 && scroll < 800){
    //     //$("#animation").attr("src", "http://coverjunction.s3.amazonaws.com/manual/low/colorful2.jpg");
    //     //$(".quotes").hide();
    //     $('.quotes').stop().fadeOut('normal', function(){
    //         $('.quote-2').stop().fadeIn();
    //     });
    // }
    // if(scroll >= 800 && scroll < 1300){
    //     //$("#animation").attr("src", "http://coverjunction.s3.amazonaws.com/manual/low/colorful3.jpg");
    //     //$(".quotes").hide();
    //     $('.quotes').stop().fadeOut('normal', function(){
    //         $('.quote-3').stop().fadeIn();
    //     });
    // }
    // if(scroll >= 1300 && scroll < 1800 ){
    //     //$("#animation").attr("src", "http://coverjunction.s3.amazonaws.com/manual/low/colorful4.jpg");
    //     //$(".quotes").hide();
    //     $('.quotes').stop().fadeOut('normal', function(){
    //         $('.quote-4').stop().fadeIn();
    //     });
    // }
    // if(scroll >= 1800 ){
    //     //$("#animation").attr("src", "http://coverjunction.s3.amazonaws.com/manual/low/colorful5.jpg");
    //     //$(".quotes").hide();
    //     $('.quotes').stop().fadeOut('normal', function(){
    //         $('.quote-5').stop().fadeIn();
    //     });
    // }

    // });


    if($(".tag-select2").length){
        $(".tag-select2").select2({
          tags: true
        });
    }

});

	$( window ).resize(function() {
        // sticky footer
        var footerHeight = $('footer').outerHeight();
        var stickFooterPush = $('.push').height(footerHeight);  
        $('.content').css({'marginBottom':'-' + footerHeight + 'px'});

		// jumbotron-banner resize
        $(".jumbotron-banner").css("min-height" , $(window).height() - $(".navbar-inverse").height()) ;
		$(".jumbotron-banner .text-container .col-md-5").height($(".jumbotron-banner .text-container .col-md-7").outerHeight()).css("position","relative");
		
        var navheight = $(".navbar-inverse").height();

        $(".jumbotron-banner").css("margin-top", navheight);

        if ($(window).width() < 667) {
    		setTimeout(function(){ 
    			$(".cb-slideshow").height($(".cb-slideshow").height());
    			$(".jumbotron-banner .text-container").css("padding-top", $(".cb-slideshow").height());
    		},300);
	   };
    });
     $(window).resize();
});